from __future__ import annotations

from pathlib import Path

from agents.base import BaseAgent
from contracts import LintResult, ModuleSpec, RTLArtifact, SimulationReport
from llm.parsing import extract_code_block
from llm.prompts import build_rtl_generation_request, build_rtl_repair_request
from tools.verilator_wrapper import lint_verilog


class RTLCoderAgent(BaseAgent):
    name = "rtl_coder"

    def generate(
        self,
        spec: ModuleSpec,
        output_path: Path,
        version: str = "v0",
        previous_source: str | None = None,
        lint_feedback: LintResult | None = None,
        sim_feedback: SimulationReport | None = None,
    ) -> RTLArtifact:
        source = self._generate_source(
            spec=spec,
            previous_source=previous_source,
            lint_feedback=lint_feedback,
            sim_feedback=sim_feedback,
        )
        output_path.write_text(source, encoding="utf-8")
        lint = lint_verilog([output_path], top_module=spec.module_name, cwd=output_path.parent)
        notes = [f"Generated by backend `{self.backend.name}`." if self.backend else "Generated by built-in template fallback."]
        if previous_source is None and self.backend is None:
            notes.append("Template generation only. Replace the backend to get prompt-driven RTL generation.")
        return RTLArtifact(
            module_name=spec.module_name,
            version=version,
            filepath=str(output_path),
            lint=lint,
            notes=notes,
        )

    def repair_from_lint(
        self,
        spec: ModuleSpec,
        previous_source: str,
        lint_feedback: LintResult,
        output_path: Path,
        version: str,
    ) -> RTLArtifact:
        return self.generate(
            spec=spec,
            output_path=output_path,
            version=version,
            previous_source=previous_source,
            lint_feedback=lint_feedback,
        )

    def repair_from_simulation(
        self,
        spec: ModuleSpec,
        previous_source: str,
        sim_feedback: SimulationReport,
        output_path: Path,
        version: str,
    ) -> RTLArtifact:
        return self.generate(
            spec=spec,
            output_path=output_path,
            version=version,
            previous_source=previous_source,
            sim_feedback=sim_feedback,
        )

    def _generate_source(
        self,
        spec: ModuleSpec,
        previous_source: str | None,
        lint_feedback: LintResult | None,
        sim_feedback: SimulationReport | None,
    ) -> str:
        if self.backend is not None:
            request = (
                build_rtl_repair_request(spec, previous_source, lint_feedback, sim_feedback)
                if previous_source is not None
                else build_rtl_generation_request(spec)
            )
            response = self.backend.generate(request)
            if response:
                return extract_code_block(response)
        return self.render_module(spec)

    def render_module(self, spec: ModuleSpec) -> str:
        parameter_block = self._render_parameters(spec)
        port_block = self._render_ports(spec)
        assigns = "\n".join(self._render_output_assign(port) for port in spec.ports if port.dir == "output")
        if not assigns:
            assigns = "  // No output ports declared."
        return "\n".join(
            [
                "`timescale 1ns/1ps",
                "/* verilator lint_off DECLFILENAME */",
                "/* verilator lint_off UNUSEDPARAM */",
                "/* verilator lint_off UNUSEDSIGNAL */",
                f"module {spec.module_name}{parameter_block} (",
                port_block,
                ");",
                "",
                "  // TODO: Replace this stub with the real RTL implementation.",
                f"  // Functional intent: {spec.functional_spec}",
                "",
                assigns,
                "",
                "endmodule",
                "/* verilator lint_on UNUSEDSIGNAL */",
                "/* verilator lint_on UNUSEDPARAM */",
                "/* verilator lint_on DECLFILENAME */",
                "",
            ]
        )

    def _render_parameters(self, spec: ModuleSpec) -> str:
        if not spec.parameters:
            return ""
        rendered = []
        for parameter in spec.parameters:
            rendered.append(f"  parameter {parameter.name} = {parameter.default}")
        return " #(\n" + ",\n".join(rendered) + "\n)"

    def _render_ports(self, spec: ModuleSpec) -> str:
        rendered = []
        for index, port in enumerate(spec.ports):
            comma = "," if index != len(spec.ports) - 1 else ""
            rendered.append(f"  {self._port_decl(port)}{comma}")
        return "\n".join(rendered)

    def _port_decl(self, port) -> str:
        width = self._width_range(port.width)
        signed = " signed" if port.signed else ""
        return f"{port.dir} wire{signed}{width} {port.name}"

    def _render_output_assign(self, port) -> str:
        literal = self._zero_literal(port.width)
        return f"  assign {port.name} = {literal};"

    @staticmethod
    def _width_range(width: int | str) -> str:
        if width == 1:
            return ""
        if isinstance(width, int):
            return f" [{width - 1}:0]"
        return f" [{width}-1:0]"

    @staticmethod
    def _zero_literal(width: int | str) -> str:
        if width == 1:
            return "1'b0"
        if isinstance(width, int):
            return "{" + f"{width}" + "{1'b0}}"
        return "{" + f"{width}" + "{1'b0}}"
