from __future__ import annotations

import logging
from pathlib import Path

from agents.base import BaseAgent
from contracts import ModuleSpec, SimulationReport, TestbenchArtifact
from llm.parsing import extract_code_block
from llm.prompts import build_tb_generation_request, build_tb_repair_request, source_from_path
from tools.verilator_wrapper import lint_verilog


class TestbenchAgent(BaseAgent):
    name = "testbench_agent"

    def generate(
        self,
        spec: ModuleSpec,
        rtl_path: Path,
        output_path: Path,
        version: str = "v0",
        previous_source: str | None = None,
        sim_feedback: SimulationReport | None = None,
    ) -> TestbenchArtifact:
        source = self._generate_source(
            spec=spec,
            rtl_path=rtl_path,
            previous_source=previous_source,
            sim_feedback=sim_feedback,
        )
        output_path.write_text(source, encoding="utf-8")
        lint = lint_verilog(
            [rtl_path, output_path],
            top_module=f"{spec.module_name}_tb",
            cwd=output_path.parent,
        )
        notes = [f"Generated by backend `{self.backend.name}`." if self.backend else "Generated by built-in template fallback."]
        if previous_source is None and self.backend is None:
            notes.append("Template generation only. Replace the backend to get prompt-driven TB generation.")
        return TestbenchArtifact(
            module_name=f"{spec.module_name}_tb",
            version=version,
            filepath=str(output_path),
            lint=lint,
            notes=notes,
        )

    def repair(
        self,
        spec: ModuleSpec,
        rtl_path: Path,
        previous_source: str,
        sim_feedback: SimulationReport,
        output_path: Path,
        version: str,
    ) -> TestbenchArtifact:
        return self.generate(
            spec=spec,
            rtl_path=rtl_path,
            output_path=output_path,
            version=version,
            previous_source=previous_source,
            sim_feedback=sim_feedback,
        )

    def _generate_source(
        self,
        spec: ModuleSpec,
        rtl_path: Path,
        previous_source: str | None,
        sim_feedback: SimulationReport | None,
    ) -> str:
        if self.backend is not None:
            rtl_source = source_from_path(rtl_path)
            request = (
                build_tb_repair_request(spec, rtl_source, previous_source, sim_feedback)
                if previous_source is not None and sim_feedback is not None
                else build_tb_generation_request(spec, rtl_source)
            )
            logging.info(f"[TB] 发送Prompt到LLM:\n{request.user_prompt}")
            response = self.backend.generate(request)
            logging.info(f"[TB] 收到LLM响应, 长度: {len(response) if response else 0}")
            if response:
                return extract_code_block(response)
        return self.render_testbench(spec)

    def render_testbench(self, spec: ModuleSpec) -> str:
        declarations = []
        connections = []
        init_lines = []
        clock_name = self._find_port(spec, {"clk", "clock"})
        localparams = self._render_localparams(spec)
        param_overrides = self._render_param_overrides(spec)
        for port in spec.ports:
            range_text = self._width_range(port.width)
            if port.dir == "input":
                declarations.append(f"  reg{range_text} {port.name};")
                init_lines.append(f"    {port.name} = {self._zero_literal(port.width)};")
            else:
                declarations.append(f"  wire{range_text} {port.name};")
            connections.append(f"    .{port.name}({port.name})")

        clock_block = self._render_clock_block(spec)
        reset_block = self._render_reset_block(spec)
        test_points = spec.test_points or ["add self-checking vectors here"]
        test_comments = "\n".join(f"    // - {point}" for point in test_points)
        dut_connections = ",\n".join(connections)
        initial_body = "\n".join(init_lines) if init_lines else "    // No input ports to initialize."
        wait_line = f"    repeat (2) @(posedge {clock_name});" if clock_name else "    #20;"
        return "\n".join(
            [
                "`timescale 1ns/1ps",
                "/* verilator lint_off DECLFILENAME */",
                "/* verilator lint_off UNUSEDPARAM */",
                "/* verilator lint_off UNUSEDSIGNAL */",
                f"module {spec.module_name}_tb;",
                "",
                *localparams,
                "",
                *declarations,
                "",
                f"  {spec.module_name}{param_overrides} dut (",
                dut_connections,
                "  );",
                "",
                clock_block,
                "",
                reset_block,
                "",
                "  initial begin",
                '    $dumpfile("wave.vcd");',
                "    $dumpvars(0, dut);",
                initial_body,
                wait_line,
                "    // TODO: Replace this section with generated stimulus and scoreboard logic.",
                "    // Target test points:",
                test_comments,
                '    $display("TB_INCOMPLETE");',
                "    $finish;",
                "  end",
                "",
                "endmodule",
                "/* verilator lint_on UNUSEDSIGNAL */",
                "/* verilator lint_on UNUSEDPARAM */",
                "/* verilator lint_on DECLFILENAME */",
                "",
            ]
        )

    def _render_clock_block(self, spec: ModuleSpec) -> str:
        clock_name = self._find_port(spec, {"clk", "clock"})
        if not clock_name:
            return "  // No dedicated clock port identified."
        return "\n".join(
            [
                "  initial begin",
                f"    {clock_name} = 1'b0;",
                "  end",
                "",
                f"  always #5 {clock_name} = ~{clock_name};",
            ]
        )

    def _render_reset_block(self, spec: ModuleSpec) -> str:
        reset_name = self._find_reset_port(spec)
        if not reset_name:
            return "  // No dedicated reset port identified."
        active_level = "1'b0" if "low" in spec.reset_strategy else "1'b1"
        inactive_level = "1'b1" if active_level == "1'b0" else "1'b0"
        return "\n".join(
            [
                "  initial begin",
                f"    {reset_name} = {active_level};",
                "    #12;",
                f"    {reset_name} = {inactive_level};",
                "  end",
            ]
        )

    @staticmethod
    def _find_port(spec: ModuleSpec, candidates: set[str]) -> str | None:
        for port in spec.ports:
            if port.name in candidates:
                return port.name
        return None

    @staticmethod
    def _find_reset_port(spec: ModuleSpec) -> str | None:
        for port in spec.ports:
            if "rst" in port.name:
                return port.name
        return None

    @staticmethod
    def _render_localparams(spec: ModuleSpec) -> list[str]:
        if not spec.parameters:
            return ["  // No parameters declared."]
        return [f"  localparam {parameter.name} = {parameter.default};" for parameter in spec.parameters]

    @staticmethod
    def _render_param_overrides(spec: ModuleSpec) -> str:
        if not spec.parameters:
            return ""
        overrides = ",\n".join(
            f"    .{parameter.name}({parameter.name})" for parameter in spec.parameters
        )
        return " #(\n" + overrides + "\n  )"

    @staticmethod
    def _width_range(width: int | str) -> str:
        if width == 1:
            return ""
        if isinstance(width, int):
            return f" [{width - 1}:0]"
        return f" [{width}-1:0]"

    @staticmethod
    def _zero_literal(width: int | str) -> str:
        if width == 1:
            return "1'b0"
        if isinstance(width, int):
            return f"{width}'b0"
        return "0"
